/** tslint:disable */
//@ts-nocheck

const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;

function writeFileUsingFs(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

const envDirectory = './src/environments';

if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

writeFileUsingFs('./src/environments/environment.prod.ts', '');
writeFileUsingFs('./environments/environment.ts', '');

const isProduction = environment === 'prod';

const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

  const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: ${isProduction},
    GOOGLE_MAPS_API_KEY: '${process.env.GOOGLE_MAPS_API_KEY}'
  };
`;

writeFileUsingFs(targetPath, environmentFileContent);

/** tslint:enable */
